name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: baby_1l_run_1

      - name: Run neutronics model
        shell: bash -l {0}
        working-directory: analysis/neutron
        run: |
          python openmc_model.py
          jupyter-nbconvert --to notebook postprocessing.ipynb --execute

      - name: Run foil analysis
        shell: bash -l {0}
        working-directory: analysis/neutron
        run: |
          papermill foil_analysis.ipynb temp.ipynb -p download_from_raw False
          jupyter-nbconvert --to notebook --execute temp.ipynb
          
      - name: Run tritium model
        shell: bash -l {0}
        working-directory: analysis/tritium
        run: jupyter-nbconvert --to notebook tritium_model.ipynb --execute
